### ISSUE TITLE
Improve javadoc formatting

### ISSUE THREAD

**Issue by danieldietrich** [vavr-io/vavr#2014]
Currently the Javadoc looks really ugly in cases we have many generics (e.g. `Try.WithResources*`). Especially the lines are _very_ long.

The following style makes the docs less hard to read by fitting the lines into the browser window and adding better line-break semantics:

```css
pre {
    white-space: pre-line !important;
}

code, tt {
    white-space: pre-wrap !important;
}
```
